zmamavisdctl, zmclamdctl, zmopendkimctl, zmsaslauthdctl,   zmfreshclamctl, zmnginxctl, zmtrainsa, zmauditswatchctl,   zmhactl, zmmemcachedctl, zmswatchctl, zmjsprecompile,   zmloggerinit, zmresetmysqlpassword, zmupdatezco, zmcbpolicydctl: removed hardcoded checks for zimbra user zmopendkimctl: do not attemp to switch to zimbra user

diff --git a/ZimbraServer/src/libexec/zmloggerinit b/ZimbraServer/src/libexec/zmloggerinit
--- a/ZimbraServer/src/libexec/zmloggerinit
+++ b/ZimbraServer/src/libexec/zmloggerinit
@@ -14,11 +14,11 @@
 # ***** END LICENSE BLOCK *****
 # 
 
-#
-if [ x`whoami` != "xzimbra" ]; then
-  echo "Error: must be run as user zimbra"
-  exit 1
-fi
+# XXX SLAPOS must run as current user
+#if [ x`whoami` != "xzimbra" ]; then
+#  echo "Error: must be run as user zimbra"
+#  exit 1
+#fi
 
 umask 027
 source `dirname $0`/../bin/zmshutil || exit 1
