disabled root check for zmmyinit

diff --git a/ZimbraServer/src/libexec/zmmyinit b/ZimbraServer/src/libexec/zmmyinit
--- a/ZimbraServer/src/libexec/zmmyinit
+++ b/ZimbraServer/src/libexec/zmmyinit
@@ -14,10 +14,11 @@
 # ***** END LICENSE BLOCK *****
 # 
 
-if [ x`whoami` != "xzimbra" ]; then
-  echo "Error: must be run as user zimbra"
-  exit 1
-fi
+## XXX SLAPOS must run as regular user
+#if [ x`whoami` != "xzimbra" ]; then
+#  echo "Error: must be run as user zimbra"
+#  exit 1
+#fi
 
 usage() {
   echo "$0 [--help] [--sql_root_pw <password>] [--mysql_memory_percent 30]"
